RegisterNetEvent('PaydayMessage')
AddEventHandler('PaydayMessage', function(salary, moneyOnBank)
	TriggerEvent("chatMessage", "", {50, 100, 168}, "^*^4-------------^7PAYDAY^4-------------")
	TriggerEvent("chatMessage", "", {255, 255, 255}, "^*Salary: ^r^2"..salary.."$")
	TriggerEvent("chatMessage", "", {255, 255, 255}, "^*Taxes: ^r^10$")
	TriggerEvent("chatMessage", "", {255, 255, 255}, "^*Payment for bussines: ^r^10$")
	TriggerEvent("chatMessage", "", {255, 255, 255}, "^*Money in bank: ^r^2"..moneyOnBank.."$")
	TriggerEvent("chatMessage", "", {50, 100, 168}, "^*^4-------------------------------------")
end)